package io.github.YSCohen.rustZmanimTestGenerator;

import java.lang.reflect.Method;
import java.time.Instant;
import java.time.LocalDate;

import com.kosherjava.zmanim.AstronomicalCalendar;
import com.kosherjava.zmanim.util.GeoLocation;

public class GenerateAcTests {
    public static void main(String[] args) {
        generateAllTests();
    }

    private static void generateAllTests() {
        System.out.print("""
                // Generated by rust-zmanim-test-generator
                // https://github.com/YSCohen/rust-zmanim-test-generator
                // This file is part of rust-zmanim, licensed under LGPL-2.1

                //! this is a set of tests for
                //! [astronomical_calculator](rust_zmanim::astronomical_calculator)

                mod test_helper;
                use jiff::civil;
                use rust_zmanim::astronomical_calculator;
                use std::iter::zip;
                """);

        GeoLocation[] locs = Helpers.getLocs();

        generateSingleTest(locs, "getSunrise", "sunrise");
        generateSingleTest(locs, "getSeaLevelSunrise", "sea_level_sunrise");

        generateSingleTest(locs, "getSunset", "sunset");
        generateSingleTest(locs, "getSeaLevelSunset", "sea_level_sunset");

        generateSingleTest(locs, "getSunTransit", "solar_noon");
        generateSingleTest(locs, "getSolarMidnight", "solar_midnight");
    }

    private static void generateSingleTest(GeoLocation[] locs, String javaMethodName, String rustFnName) {
        try {
            String[] results = new String[locs.length];
            LocalDate ld = LocalDate.of(2017, 10, 17);
            for (int i = 0; i < locs.length; i++) {
                AstronomicalCalendar acOfLocation = new AstronomicalCalendar(locs[i]);
                acOfLocation.setLocalDate(ld);

                Method method = acOfLocation.getClass().getMethod(javaMethodName, new Class<?>[0]);
                Instant value = (Instant) method.invoke(acOfLocation);
                results[i] = Helpers.formatDate(value, locs[i].getZoneId(), "yyyy-MM-dd HH:mm:ss.SSS z");
            }

            System.out.printf(
                    """

                            #[test]
                            fn test_%s() {
                                let locations = test_helper::more_locations();
                                let expected_datetime_strs = [
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                    "%s",
                                ];

                                for (loc, edt) in zip(locations, expected_datetime_strs) {
                                    let date = civil::date(2017, 10, 17);
                                    let result = match astronomical_calculator::%s(&date, &loc) {
                                        Some(dt) => dt.strftime("%s").to_string(),
                                        None => String::from("None"),
                                    };
                                    assert_eq!(result, edt)
                                }
                            }
                            """,
                    rustFnName, results[0], results[1],
                    results[2], results[3], results[4],
                    results[5].replace("GMT+14:00", "+14").replace("WSDT", "+14"),
                    results[6].replace("GMT+12:00", "+12"),
                    results[7].replace("HADT", "HDT"),
                    results[8].replace("GMT-11:00", "-11"),
                    rustFnName, "%Y-%m-%d %H:%M:%S.%3f %Z");
        } catch (Exception e) {
            System.out.println("\n// Could not invoke " + javaMethodName + " because " + e.getMessage());
        }
    }
}
